\input texinfo   @c -*-texinfo-*-
@c %**start of header
@setfilename Simple_Jpeg_Lib.info
@settitle SIMPLE_JPEG_LIB MANUAL
@setchapternewpage odd
@c %**end of header
    
@ifinfo
This file documents ... 
     
Copyright 2003-2006 Patrice Freydiere
     
Permission is granted to ...  

@end ifinfo
     
@c  This title page illustrates only one of the
@c  two methods of forming a title page.
     
@titlepage
@title Simple_Jpeg_Lib Manual
@subtitle a simple Ada thick binding to the jpeglib
@author Patrice Freydiere
     
@c  The following two commands
@c  start the copyright page.
@page
@vskip 0pt plus 1filll
 Copyright @copyright{} 2003-2004 Patrice Freydiere
   
     
Permission is granted to use any material found in this manual ...
@end titlepage
     
@node Top, Introduction, (dir), (dir)
@comment  node-name,  next,  previous,  up     

@ifinfo
This document describes how to use Simple_Jpeg_Lib

@end ifinfo

@menu
* Introduction::                What is Imgsvr ...
* Compiling::                   
* Simple_Jpeg_Lib::             
@end menu

@node    Introduction, Compiling, Top, Top
@comment node-name,     next,           previous, up
@chapter Introduction to the simple_jpeg_lib
@cindex Introduction

@strong{Simple_Jpeg_Lib} is a simple library that permit to load, save and use jpeg files. This library provide a simple set of functions for jpeg manipulation.


@node Compiling, Simple_Jpeg_Lib, Introduction, Top
@chapter Compiling Ada programs with the Simple_Jpeg_Lib

Simple_Jpeg_Lib contains a small c wrapper to easy the binding with the jpeglib. this wapper @strong{c_simple_jpeg_lib.c} must be compiled with the same compiler of the jpeglib, or the same compile options (internal jpeglib structures must have the same definition in the jpeglib and in the wrapper).

@subsection compiling the simple_jpeg_lib

@verbatim

rem
rem Simple script for compiling Ada Jpeg Bindings
rem 

gcc -c -g c_simple_jpeg_lib.c -I../Dependencies/jpeg-6b

gnatmake -c -g -gnatf simple_jpeg_lib.adb

@end verbatim


@subsection compiling a program with the simple_jpeg_lib

To compile your program, you must first compile the simple_jpeg_lib, and then link to your program :
@itemize
@item c_simple_jpeg_lib.o
@item libjpeglib.a
@end itemize

Example :

@example

gcc -c  ../src/c_simple_jpeg_lib.c -I../Dependencies/jpeg-6b

gnatmake -g -gnatf -gnatov -gnaty -I../src test_jpeg_reader -largs c_simple_jpeg_lib.o -ljpeg -bargs -E


@end example


@node Simple_Jpeg_Lib,  , Compiling, Top
@chapter Using the simple_jpeg_lib

@section reading a jpeg file

@example

with simple_jpeg_lib;
use simple_jpeg_lib;

procedure test_jpeg_reader is

   J : Jpeg_Handle_decompress;
   JC : Jpeg_Handle_Compress;
   I:Integer := 0;

begin

       -- open image, and decompress it with 1/8 of the original size
      Open_Jpeg("sample.jpg",J,8);

      -- Get Informations
      declare
         W,H : Dimension ;
         Jpegtype : Jpeg_Type;
      begin
         Get_Image_Info(J,W,H,jpegtype);

         Text_Io.Put(" Width :" & dimension'Image(W)
                     & " , height " & dimension'Image(h)
                     & " , nb comp : " & Jpeg_type'Image(jpegtype) );

         Create_Jpeg("output.jpg",Jc,W,H,jpegtype);
      end;

      declare
      begin
         while True loop
            declare
               Comp : Component_Array := Read_Next_Line(J);
            begin
               Write_Line(JC,Comp);
               I:=I+1; -- count the lines
            end;
         end loop;
      exception
         when JPEG_EXCEPTION  =>
            null;
      end;

      Text_Io.New_Line;
      Text_Io.Put( Integer'Image(I) & " read Lines ");

      Close_Jpeg(J);
      Close_Jpeg(jc);

      Text_Io.Put("End  ");
      Text_Io.New_Line;

exception
        when E : others =>
           Text_IO.Put_Line (GNAT.Traceback.Symbolic.Symbolic_Traceback (E));

end;

@end example


@unnumbered Concept Index
     
@printindex cp
     
@contents
@bye

